<#
.SYNOPSIS
    Exports the full live data + schema of the AgenticCommerce SQL Server database
    into three portable artefacts committed to the repo:
      1. scripts/seed-data.sql   - self-contained T-SQL restore (data records)
      2. schema/schema.txt       - all table DDL (CREATE TABLE ...)
      3. schema/data.xlsx        - one Excel worksheet per table holding its records
    Applying seed-data.sql on any machine (after `dotnet ef database update`)
    re-syncs every user table to exactly match this machine.

.DESCRIPTION
    This script uses ADO.NET (System.Data.SqlClient) rather than parsing sqlcmd
    text output, so string/date/GUID quoting, NULLs and identity columns are all
    handled deterministically.

    Record restore is REPLACE / re-sync: every user table is deleted and
    re-inserted (identity values preserved via IDENTITY_INSERT, identity seeds
    reset via DBCC CHECKIDENT). FK enforcement is disabled around the writes and
    re-enabled + validated afterwards, so write order does not matter.

    Transient / secret-bearing tables (EmployeeLogs, CustomerLogs,
    ConversationHistories) are EXCLUDED - they hold active JWT session tokens and
    developer chat history, which must not travel in git.

.PARAMETER Server    SQL Server host[:port]. Default "localhost,1433".
.PARAMETER Database  Source database. Default "AgenticCommerceDB".
.PARAMETER User      SQL login. Default "sa".
.PARAMETER Password  SQL password. Uses $env:SQL_SA_PASSWORD if omitted.

.EXAMPLE
    $env:SQL_SA_PASSWORD = 'YourStrong!Passw0rd'
    ./scripts/export-data.ps1
#>
param(
    [string]$Server   = "localhost,1433",
    [string]$Database = "AgenticCommerceDB",
    [string]$User     = "sa",
    [string]$Password = ""
)

$ErrorActionPreference = "Stop"

if (-not $Password) { $Password = $env:SQL_SA_PASSWORD }
if (-not $Password) { $Password = Read-Host "SQL password for $User@$Server" }

Add-Type -AssemblyName System.Data
try { Add-Type -AssemblyName Microsoft.Office.Interop.Excel } catch { }

$root = Split-Path -Parent $PSScriptRoot
$seedOut = Join-Path $PSScriptRoot "seed-data.sql"
$schemaDir = Join-Path $root "schema"
$schemaTxtOut = Join-Path $schemaDir "schema.txt"
$xlsxOut = Join-Path $schemaDir "data.xlsx"
New-Item -ItemType Directory -Path $schemaDir -Force | Out-Null

$connString = "Server=$Server;Database=$Database;User Id=$User;Password=$Password;TrustServerCertificate=True;"
$conn = New-Object System.Data.SqlClient.SqlConnection $connString
$conn.Open()
Write-Host "Connected to $Database on $Server"

function Get-Tables {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = "SELECT t.name FROM sys.tables t WHERE t.name <> '__EFMigrationsHistory' AND t.name NOT IN ('EmployeeLogs','CustomerLogs','ConversationHistories') ORDER BY t.name"
    $r = $cmd.ExecuteReader()
    $list = New-Object System.Collections.Generic.List[string]
    while ($r.Read()) { $list.Add($r.GetString(0)) }
    $r.Close()
    return @($list)
}

function Get-Columns([string]$table) {
    $cmd = $conn.CreateCommand()
    $cmd.CommandText = @"
SELECT c.name, TYPE_NAME(c.user_type_id) AS typ,
       CASE WHEN c.is_identity = 1 THEN 1 ELSE 0 END AS is_id,
       c.max_length, c.precision, c.scale, c.is_nullable
FROM sys.columns c WHERE c.object_id = OBJECT_ID('$table') ORDER BY c.column_id
"@
    $r = $cmd.ExecuteReader()
    $cols = New-Object System.Collections.ArrayList
    while ($r.Read()) {
        [void]$cols.Add([pscustomobject]@{
            Name = $r.GetString(0); Type = $r.GetString(1); IsId = ($r.GetInt32(2) -eq 1)
            MaxLen = $r.GetInt16(3); Prec = $r.GetByte(4); Scale = $r.GetByte(5); Nullable = $r.GetBoolean(6)
        })
    }
    $r.Close()
    return @($cols)
}

$Quote = { param($v) if ($null -eq $v) { return 'NULL' }; if ($v -is [System.DBNull]) { return 'NULL' }; return "'" + ([string]$v).Replace("'", "''") + "'" }

# ---------- build seed-data.sql (records) ----------
$tables = Get-Tables
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* Auto-generated by scripts/export-data.ps1 from database '$Database'. DO NOT EDIT BY HAND. */")
[void]$sb.AppendLine("SET NOCOUNT ON;")
[void]$sb.AppendLine("SET XACT_ABORT ON;")
[void]$sb.AppendLine("BEGIN TRANSACTION;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- Disable FK enforcement so delete/insert order is irrelevant.")
foreach ($t in $tables) { [void]$sb.AppendLine("ALTER TABLE [$t] NOCHECK CONSTRAINT ALL;") }
[void]$sb.AppendLine("")
foreach ($t in $tables) { [void]$sb.AppendLine("DELETE FROM [$t];") }
[void]$sb.AppendLine("")

$idTables = @()
foreach ($t in $tables) {
    $cols = @(Get-Columns $t)
    if ($cols.Count -eq 0) { continue }
    $idCol = $cols | Where-Object { $_.IsId } | Select-Object -First 1
    if ($idCol) { [void]$sb.AppendLine("SET IDENTITY_INSERT [$t] ON;"); $idTables += $t }

    $colList = ($cols | ForEach-Object { "[$($_.Name)]" }) -join ", "

    $cmd = $conn.CreateCommand()
    $cmd.CommandText = "SELECT * FROM [$t]"
    $dr = $cmd.ExecuteReader()
    $nCols = $dr.FieldCount
    while ($dr.Read()) {
        $vals = @()
        for ($i = 0; $i -lt $nCols; $i++) {
            if ($dr.IsDBNull($i)) { $vals += 'NULL'; continue }
            $raw = $dr.GetValue($i)
            $col = $cols[$i]
            switch -Regex ($col.Type) {
                '(?i)^(bit)$' { if ($raw) { $vals += '1' } else { $vals += '0' } }
                '(?i)^(int|bigint|smallint|tinyint|decimal|numeric|money|smallmoney|float|real)$' { $vals += ([string]$raw) }
                '(?i)^(uniqueidentifier)$' { $vals += "'" + ([string]$raw) + "'" }
                '(?i)^(datetime|datetime2|datetimeoffset|smalldatetime|date|time)$' { $vals += "'" + $raw.ToString("yyyy-MM-dd HH:mm:ss.fffffff") + "'" }
                default { $vals += "'" + ([string]$raw).Replace("'", "''") + "'" }
            }
        }
        [void]$sb.AppendLine("INSERT INTO [$t] ($colList) VALUES (" + ($vals -join ", ") + ");")
    }
    $dr.Close()

    if ($idCol) { [void]$sb.AppendLine("SET IDENTITY_INSERT [$t] OFF;") }
    [void]$sb.AppendLine("")
}

foreach ($t in $idTables) {
    [void]$sb.AppendLine("IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('$t') AND last_value IS NOT NULL)")
    [void]$sb.AppendLine("BEGIN DBCC CHECKIDENT ('$t', RESEED); END")
}
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- Re-enable and validate FK constraints.")
foreach ($t in $tables) { [void]$sb.AppendLine("ALTER TABLE [$t] WITH CHECK CHECK CONSTRAINT ALL;") }
[void]$sb.AppendLine("")
[void]$sb.AppendLine("COMMIT TRANSACTION;")
[void]$sb.AppendLine("GO")
[System.IO.File]::WriteAllText($seedOut, $sb.ToString())
Write-Host "  wrote $seedOut"

# ---------- build schema.txt (DDL) ----------
$sbt = New-Object System.Text.StringBuilder
[void]$sbt.AppendLine("AgenticCommerce Platform - Database Schema")
[void]$sbt.AppendLine("Generated from database '$Database' on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
[void]$sbt.AppendLine("Contains CREATE TABLE DDL for every user table (records live in data.xlsx / seed-data.sql).")
[void]$sbt.AppendLine("=" * 80)

$pkCmd = $conn.CreateCommand()
$pkCmd.CommandText = @"
SELECT OBJECT_NAME(i.object_id) AS tbl, c.name AS col
FROM sys.indexes i
JOIN sys.index_columns ic ON i.object_id=ic.object_id AND i.index_id=ic.index_id
JOIN sys.columns c ON ic.object_id=c.object_id AND ic.column_id=c.column_id
WHERE i.is_primary_key=1 ORDER BY tbl, ic.key_ordinal
"@
$pkMap = @{}
$pr = $pkCmd.ExecuteReader()
while ($pr.Read()) {
    $tb = $pr.GetString(0)
    if (-not $pkMap.ContainsKey($tb)) { $pkMap[$tb] = New-Object System.Collections.Generic.List[string] }
    $pkMap[$tb].Add($pr.GetString(1))
}
$pr.Close()

$fkCmd = $conn.CreateCommand()
$fkCmd.CommandText = @"
SELECT OBJECT_NAME(fk.parent_object_id) AS child, c.name AS col, OBJECT_NAME(fk.referenced_object_id) AS parent, rc.name AS refcol
FROM sys.foreign_keys fk
JOIN sys.foreign_key_columns fkc ON fk.object_id=fkc.constraint_object_id
JOIN sys.columns c ON fkc.parent_object_id=c.object_id AND fkc.parent_column_id=c.column_id
JOIN sys.columns rc ON fkc.referenced_object_id=rc.object_id AND fkc.referenced_column_id=rc.column_id
ORDER BY child, fkc.constraint_column_id
"@
$fkList = New-Object System.Collections.Generic.List[string]
$fr = $fkCmd.ExecuteReader()
while ($fr.Read()) {
    $fkList.Add("ALTER TABLE [$($fr.GetString(0))] ADD CONSTRAINT [FK_$($fr.GetString(0))_$($fr.GetString(2))] FOREIGN KEY ([$($fr.GetString(1))]) REFERENCES [$($fr.GetString(2))]([$($fr.GetString(3))]);")
}
$fr.Close()

foreach ($t in $tables) {
    $cols = @(Get-Columns $t)
    [void]$sbt.AppendLine("")
    [void]$sbt.AppendLine("CREATE TABLE [$t] (")
    $dcl = New-Object System.Collections.Generic.List[string]
    foreach ($c in $cols) {
        $d = "    [$($c.Name)] $($c.Type)"
        if ($c.Type -in @('varchar','nvarchar','char','nchar','binary','varbinary')) {
            if ($c.MaxLen -eq -1) { $d += "(max)" } else { $d += "($($c.MaxLen))" }
        } elseif ($c.Type -in @('decimal','numeric')) { $d += "($($c.Prec),$($c.Scale))" }
        if ($c.IsId) { $d += " IDENTITY(1,1)" }
        if (-not $c.Nullable) { $d += " NOT NULL" }
        $dcl.Add($d)
    }
    if ($pkMap.ContainsKey($t)) { $dcl.Add("    PRIMARY KEY ([" + ($pkMap[$t] -join "], [") + "])") }
    [void]$sbt.AppendLine(($dcl -join ",`r`n"))
    [void]$sbt.AppendLine(");")
}
[void]$sbt.AppendLine("")
[void]$sbt.AppendLine("-- Foreign key constraints")
foreach ($fk in $fkList) { [void]$sbt.AppendLine($fk) }
[System.IO.File]::WriteAllText($schemaTxtOut, $sbt.ToString())
Write-Host "  wrote $schemaTxtOut"

# ---------- build data.xlsx (Excel, one sheet per table) ----------
try {
    $excel = New-Object -ComObject Excel.Application
    $excel.Visible = $false
    $excel.DisplayAlerts = $false
    $wb = $excel.Workbooks.Add()
    while ($wb.Worksheets.Count -gt 1) { $wb.Worksheets.Item($wb.Worksheets.Count).Delete() }

    $first = $true
    foreach ($t in $tables) {
        $cols = @(Get-Columns $t)
        if ($cols.Count -eq 0) { continue }
        if ($first) { $ws = $wb.Worksheets.Item(1); $first = $false }
        else { $ws = $wb.Worksheets.Add([System.Reflection.Missing]::Value, $wb.Worksheets.Item($wb.Worksheets.Count)) }
        $ws.Name = $t.Substring(0, [Math]::Min(31, $t.Length))

        $cmd = $conn.CreateCommand()
        $cmd.CommandText = "SELECT * FROM [$t]"
        $dr = $cmd.ExecuteReader()
        $nCols = $dr.FieldCount
        $cap = 16
        $data = New-Object 'object[,]' $cap, $nCols
        for ($i = 0; $i -lt $nCols; $i++) { $data[0, $i] = $cols[$i].Name }
        $r = 1
        while ($dr.Read()) {
            if ($r -ge $cap) { $old = $data; $cap *= 2; $data = New-Object 'object[,]' $cap, $nCols; [Array]::Copy($old, $data, $old.Length) }
            for ($i = 0; $i -lt $nCols; $i++) {
                if ($dr.IsDBNull($i)) { continue }
                $v = $dr.GetValue($i)
                if ($v -is [byte[]]) { $v = [System.Text.Encoding]::UTF8.GetString($v) }
                elseif ($v -is [DateTime]) { $v = $v.ToString("yyyy-MM-dd HH:mm:ss.fffffff") }
                elseif ($v -is [bool]) { $v = 1 -band [int][bool]$v }
                $data[$r, $i] = $v
            }
            $r++
        }
        $dr.Close()
        if ($r -ge 2) {
            $range = $ws.Range($ws.Cells.Item(1, 1), $ws.Cells.Item($r - 1, $nCols))
            $range.Value2 = $data
        }
        $ws.Columns.AutoFit() | Out-Null
    }
    if (Test-Path $xlsxOut) { Remove-Item $xlsxOut -Force }
    $wb.SaveAs($xlsxOut, 51)
    $wb.Close($false)
    $excel.Quit()
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($wb) | Out-Null
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($excel) | Out-Null
    Write-Host "  wrote $xlsxOut"
} catch {
    $msg = "Excel generation failed: $($_.Exception.Message)`n" + $_.ScriptStackTrace
    Write-Warning $msg
}

$conn.Close()
Write-Host "Done."
