/* Auto-generated by scripts/export-data.ps1 from database 'AgenticCommerceDB'. DO NOT EDIT BY HAND. */
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

-- Disable FK enforcement so delete/insert order is irrelevant.
ALTER TABLE [CartItems] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Carts] NOCHECK CONSTRAINT ALL;
ALTER TABLE [CategoryMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [CreditNoteItems] NOCHECK CONSTRAINT ALL;
ALTER TABLE [CreditNotes] NOCHECK CONSTRAINT ALL;
ALTER TABLE [CustomerMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [DebitNoteItems] NOCHECK CONSTRAINT ALL;
ALTER TABLE [DebitNotes] NOCHECK CONSTRAINT ALL;
ALTER TABLE [DepartmentMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [EmployeeMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [LedgerEntries] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Ledgers] NOCHECK CONSTRAINT ALL;
ALTER TABLE [OrderItems] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Orders] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Payments] NOCHECK CONSTRAINT ALL;
ALTER TABLE [ProductMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Products] NOCHECK CONSTRAINT ALL;
ALTER TABLE [ProductStocks] NOCHECK CONSTRAINT ALL;
ALTER TABLE [PurchaseOrderItems] NOCHECK CONSTRAINT ALL;
ALTER TABLE [PurchaseOrders] NOCHECK CONSTRAINT ALL;
ALTER TABLE [RawMaterialMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [RawMaterialStocks] NOCHECK CONSTRAINT ALL;
ALTER TABLE [Receipts] NOCHECK CONSTRAINT ALL;
ALTER TABLE [SalesOrderItems] NOCHECK CONSTRAINT ALL;
ALTER TABLE [SalesOrders] NOCHECK CONSTRAINT ALL;
ALTER TABLE [StockAdjustments] NOCHECK CONSTRAINT ALL;
ALTER TABLE [StockTransactions] NOCHECK CONSTRAINT ALL;
ALTER TABLE [StockTransfers] NOCHECK CONSTRAINT ALL;
ALTER TABLE [SubCategoryMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [sysdiagrams] NOCHECK CONSTRAINT ALL;
ALTER TABLE [UnitMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [UserTypeMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [VendorMasters] NOCHECK CONSTRAINT ALL;
ALTER TABLE [WarehouseMasters] NOCHECK CONSTRAINT ALL;

DELETE FROM [CartItems];
DELETE FROM [Carts];
DELETE FROM [CategoryMasters];
DELETE FROM [CreditNoteItems];
DELETE FROM [CreditNotes];
DELETE FROM [CustomerMasters];
DELETE FROM [DebitNoteItems];
DELETE FROM [DebitNotes];
DELETE FROM [DepartmentMasters];
DELETE FROM [EmployeeMasters];
DELETE FROM [LedgerEntries];
DELETE FROM [Ledgers];
DELETE FROM [OrderItems];
DELETE FROM [Orders];
DELETE FROM [Payments];
DELETE FROM [ProductMasters];
DELETE FROM [Products];
DELETE FROM [ProductStocks];
DELETE FROM [PurchaseOrderItems];
DELETE FROM [PurchaseOrders];
DELETE FROM [RawMaterialMasters];
DELETE FROM [RawMaterialStocks];
DELETE FROM [Receipts];
DELETE FROM [SalesOrderItems];
DELETE FROM [SalesOrders];
DELETE FROM [StockAdjustments];
DELETE FROM [StockTransactions];
DELETE FROM [StockTransfers];
DELETE FROM [SubCategoryMasters];
DELETE FROM [sysdiagrams];
DELETE FROM [UnitMasters];
DELETE FROM [UserTypeMasters];
DELETE FROM [VendorMasters];
DELETE FROM [WarehouseMasters];

SET IDENTITY_INSERT [CartItems] ON;
SET IDENTITY_INSERT [CartItems] OFF;

SET IDENTITY_INSERT [Carts] ON;
SET IDENTITY_INSERT [Carts] OFF;

SET IDENTITY_INSERT [CategoryMasters] ON;
INSERT INTO [CategoryMasters] ([CategoryId], [CategoryName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (1, 'Electronics', 1, NULL, '2026-08-30 11:56:15.4220000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [CategoryMasters] ([CategoryId], [CategoryName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (2, 'Audio', 1, NULL, '2026-08-30 11:56:15.4220000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [CategoryMasters] ([CategoryId], [CategoryName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (3, 'Accessories', 1, NULL, '2026-09-02 06:49:57.1900000', NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [CategoryMasters] OFF;

SET IDENTITY_INSERT [CreditNoteItems] ON;
SET IDENTITY_INSERT [CreditNoteItems] OFF;

SET IDENTITY_INSERT [CreditNotes] ON;
SET IDENTITY_INSERT [CreditNotes] OFF;

SET IDENTITY_INSERT [CustomerMasters] ON;
INSERT INTO [CustomerMasters] ([CustomerId], [UniqueId], [Email], [PasswordHash], [FirstName], [LastName], [PhoneNumber], [AddressLine], [City], [State], [Country], [Pincode], [IsActive], [CreatedAt], [UpdatedAt], [DeletedAt]) VALUES (1, '0b36eb5f-b9b0-4edf-9aba-e37f17cb016d', 'demo@example.com', '297BD4BA3EA22ABDBAE610566A9DA4E3.DE7F3AB72C869EA62BC59BFEA27D191DCDB6B7E3EB3895FFDC79387EE5F35523', 'Demo', 'Customer', '9876543210', '1 Demo Street', 'Pune', 'Maharashtra', 'India', '411001', 1, '2026-09-02 06:49:59.5300000', NULL, NULL);
SET IDENTITY_INSERT [CustomerMasters] OFF;

SET IDENTITY_INSERT [DebitNoteItems] ON;
SET IDENTITY_INSERT [DebitNoteItems] OFF;

SET IDENTITY_INSERT [DebitNotes] ON;
SET IDENTITY_INSERT [DebitNotes] OFF;

SET IDENTITY_INSERT [DepartmentMasters] ON;
INSERT INTO [DepartmentMasters] ([DepartmentId], [DepartmentName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (1, 'CEO', NULL, '2026-01-01 00:00:00.0000000', NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [DepartmentMasters] OFF;

SET IDENTITY_INSERT [EmployeeMasters] ON;
INSERT INTO [EmployeeMasters] ([EmployeeId], [UniqueId], [Email], [PasswordHash], [FirstName], [LastName], [PhoneNumber], [DepartmentId], [UserTypeId], [IsActive], [CreatedBy], [CreatedAt], [UpdatedAt], [DeletedAt]) VALUES (1, '2143ceff-42b7-43a1-9211-8823b90b3780', 'bhaktiraut857@gmail.com', '6E0E31A5812DF35036543C37ED624FE3.5E3786E22D0A5E8F0255825FA3AAEB755554AAE484763BF7E161E0A7F7FC7970', 'Bhaktiraut', 'Raut', NULL, 1, 1, 1, NULL, '2026-09-02 06:50:01.2966667', NULL, NULL);
SET IDENTITY_INSERT [EmployeeMasters] OFF;

SET IDENTITY_INSERT [LedgerEntries] ON;
SET IDENTITY_INSERT [LedgerEntries] OFF;

SET IDENTITY_INSERT [Ledgers] ON;
SET IDENTITY_INSERT [Ledgers] OFF;

SET IDENTITY_INSERT [OrderItems] ON;
SET IDENTITY_INSERT [OrderItems] OFF;


SET IDENTITY_INSERT [Payments] ON;
SET IDENTITY_INSERT [Payments] OFF;

SET IDENTITY_INSERT [ProductMasters] ON;
INSERT INTO [ProductMasters] ([ProductId], [ProductCode], [ProductName], [CategoryId], [SubCategoryId], [UnitId], [PurchasePrice], [SellingPrice], [GSTPercent], [IsActive], [Approval1By], [Approval1At], [Approval2By], [Approval2At], [Approval3By], [Approval3At], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (1, 'PRD-001', 'Laptop', 1, NULL, 1, 700.00, 999.99, 18.00, 1, 1, '2026-08-30 11:56:15.5390000', 1, '2026-08-30 11:56:15.5390000', 1, '2026-08-30 11:56:15.5390000', NULL, '2026-08-30 11:56:15.5390000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [ProductMasters] ([ProductId], [ProductCode], [ProductName], [CategoryId], [SubCategoryId], [UnitId], [PurchasePrice], [SellingPrice], [GSTPercent], [IsActive], [Approval1By], [Approval1At], [Approval2By], [Approval2At], [Approval3By], [Approval3At], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (2, 'PRD-002', 'Smartphone', 1, NULL, 1, 450.00, 699.99, 18.00, 1, 1, '2026-08-30 11:56:15.5390000', 1, '2026-08-30 11:56:15.5390000', 1, '2026-08-30 11:56:15.5390000', NULL, '2026-08-30 11:56:15.5390000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [ProductMasters] ([ProductId], [ProductCode], [ProductName], [CategoryId], [SubCategoryId], [UnitId], [PurchasePrice], [SellingPrice], [GSTPercent], [IsActive], [Approval1By], [Approval1At], [Approval2By], [Approval2At], [Approval3By], [Approval3At], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (3, 'PRD-003', 'Headphones', 2, NULL, 1, 50.00, 89.99, 12.00, 1, 1, '2026-08-31 06:58:33.0000000', 1, '2026-08-31 06:58:33.0000000', 1, '2026-08-31 06:58:33.0000000', NULL, '2026-09-02 06:50:04.1300000', NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [ProductMasters] OFF;

SET IDENTITY_INSERT [Products] ON;
INSERT INTO [Products] ([Id], [SKU], [Name], [Description], [Price], [Cost], [Category], [StockQuantity], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (1, 'P001', 'Laptop', NULL, 999.99, 800.00, 'Electronics', 10, 1, '2026-08-30 11:56:15.7920000', NULL);
INSERT INTO [Products] ([Id], [SKU], [Name], [Description], [Price], [Cost], [Category], [StockQuantity], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (2, 'P002', 'Smartphone', NULL, 699.99, 500.00, 'Electronics', 15, 1, '2026-08-30 11:56:15.7920000', NULL);
INSERT INTO [Products] ([Id], [SKU], [Name], [Description], [Price], [Cost], [Category], [StockQuantity], [IsActive], [CreatedAt], [UpdatedAt]) VALUES (3, 'P003', 'Headphones', NULL, 89.99, 60.00, 'Audio', 50, 1, '2026-09-02 06:50:06.9100000', NULL);
SET IDENTITY_INSERT [Products] OFF;

SET IDENTITY_INSERT [ProductStocks] ON;
INSERT INTO [ProductStocks] ([ProductStockId], [ProductId], [WarehouseId], [Quantity], [ReservedQuantity], [UpdatedDate]) VALUES (1, 1, 1, 50.000, 0.000, '2026-08-30 11:56:15.7300000');
INSERT INTO [ProductStocks] ([ProductStockId], [ProductId], [WarehouseId], [Quantity], [ReservedQuantity], [UpdatedDate]) VALUES (2, 2, 1, 50.000, 0.000, '2026-08-30 11:56:15.7430000');
INSERT INTO [ProductStocks] ([ProductStockId], [ProductId], [WarehouseId], [Quantity], [ReservedQuantity], [UpdatedDate]) VALUES (3, 3, 1, 50.000, 0.000, '2026-09-02 06:50:08.3166667');
SET IDENTITY_INSERT [ProductStocks] OFF;

SET IDENTITY_INSERT [PurchaseOrderItems] ON;
SET IDENTITY_INSERT [PurchaseOrderItems] OFF;

SET IDENTITY_INSERT [PurchaseOrders] ON;
SET IDENTITY_INSERT [PurchaseOrders] OFF;

SET IDENTITY_INSERT [RawMaterialMasters] ON;
SET IDENTITY_INSERT [RawMaterialMasters] OFF;

SET IDENTITY_INSERT [RawMaterialStocks] ON;
SET IDENTITY_INSERT [RawMaterialStocks] OFF;

SET IDENTITY_INSERT [Receipts] ON;
SET IDENTITY_INSERT [Receipts] OFF;

SET IDENTITY_INSERT [SalesOrderItems] ON;
SET IDENTITY_INSERT [SalesOrderItems] OFF;

SET IDENTITY_INSERT [SalesOrders] ON;
SET IDENTITY_INSERT [SalesOrders] OFF;

SET IDENTITY_INSERT [StockAdjustments] ON;
SET IDENTITY_INSERT [StockAdjustments] OFF;

SET IDENTITY_INSERT [StockTransactions] ON;
SET IDENTITY_INSERT [StockTransactions] OFF;

SET IDENTITY_INSERT [StockTransfers] ON;
SET IDENTITY_INSERT [StockTransfers] OFF;

SET IDENTITY_INSERT [SubCategoryMasters] ON;
SET IDENTITY_INSERT [SubCategoryMasters] OFF;

SET IDENTITY_INSERT [sysdiagrams] ON;
SET IDENTITY_INSERT [sysdiagrams] OFF;

SET IDENTITY_INSERT [UnitMasters] ON;
INSERT INTO [UnitMasters] ([UnitId], [UnitName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (1, 'Piece', 1, NULL, '2026-08-30 11:56:15.2980000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [UnitMasters] ([UnitId], [UnitName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (2, 'Kg', 1, NULL, '2026-08-30 11:56:15.2990000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [UnitMasters] ([UnitId], [UnitName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (3, 'Litre', 1, NULL, '2026-08-30 11:56:15.2990000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [UnitMasters] ([UnitId], [UnitName], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (4, 'Box', 1, NULL, '2026-09-02 06:50:12.4766667', NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [UnitMasters] OFF;

SET IDENTITY_INSERT [UserTypeMasters] ON;
INSERT INTO [UserTypeMasters] ([UserTypeId], [UserTypeName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (1, 'MasterAdmin', NULL, '2026-01-01 00:00:00.0000000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [UserTypeMasters] ([UserTypeId], [UserTypeName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (2, 'Admin', NULL, '2026-01-01 00:00:00.0000000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [UserTypeMasters] ([UserTypeId], [UserTypeName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (3, 'Senior', NULL, '2026-01-01 00:00:00.0000000', NULL, NULL, NULL, NULL, NULL);
INSERT INTO [UserTypeMasters] ([UserTypeId], [UserTypeName], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (4, 'Junior', NULL, '2026-01-01 00:00:00.0000000', NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [UserTypeMasters] OFF;

SET IDENTITY_INSERT [VendorMasters] ON;
SET IDENTITY_INSERT [VendorMasters] OFF;

SET IDENTITY_INSERT [WarehouseMasters] ON;
INSERT INTO [WarehouseMasters] ([WarehouseId], [WarehouseName], [Address], [City], [State], [Pincode], [IsActive], [CreatedBy], [CreatedAt], [ModifiedBy], [ModifiedAt], [DeletedBy], [DeletedAt], [LogId]) VALUES (1, 'WH-001', 'Main Warehouse', 'Industrial Area', 'Pune', 'Maharashtra', 1, 1, '2026-09-02 06:50:14.7600000', NULL, NULL, NULL, NULL, NULL);
SET IDENTITY_INSERT [WarehouseMasters] OFF;

IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('CartItems') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('CartItems', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('Carts') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('Carts', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('CategoryMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('CategoryMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('CreditNoteItems') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('CreditNoteItems', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('CreditNotes') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('CreditNotes', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('CustomerMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('CustomerMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('DebitNoteItems') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('DebitNoteItems', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('DebitNotes') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('DebitNotes', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('DepartmentMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('DepartmentMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('EmployeeMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('EmployeeMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('LedgerEntries') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('LedgerEntries', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('Ledgers') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('Ledgers', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('OrderItems') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('OrderItems', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('Payments') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('Payments', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('ProductMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('ProductMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('Products') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('Products', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('ProductStocks') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('ProductStocks', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('PurchaseOrderItems') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('PurchaseOrderItems', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('PurchaseOrders') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('PurchaseOrders', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('RawMaterialMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('RawMaterialMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('RawMaterialStocks') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('RawMaterialStocks', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('Receipts') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('Receipts', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('SalesOrderItems') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('SalesOrderItems', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('SalesOrders') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('SalesOrders', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('StockAdjustments') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('StockAdjustments', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('StockTransactions') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('StockTransactions', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('StockTransfers') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('StockTransfers', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('SubCategoryMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('SubCategoryMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('sysdiagrams') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('sysdiagrams', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('UnitMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('UnitMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('UserTypeMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('UserTypeMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('VendorMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('VendorMasters', RESEED); END
IF EXISTS (SELECT 1 FROM sys.identity_columns WHERE object_id=OBJECT_ID('WarehouseMasters') AND last_value IS NOT NULL)
BEGIN DBCC CHECKIDENT ('WarehouseMasters', RESEED); END

-- Re-enable and validate FK constraints.
ALTER TABLE [CartItems] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [Carts] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [CategoryMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [CreditNoteItems] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [CreditNotes] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [CustomerMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [DebitNoteItems] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [DebitNotes] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [DepartmentMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [EmployeeMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [LedgerEntries] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [Ledgers] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [OrderItems] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [Orders] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [Payments] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [ProductMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [Products] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [ProductStocks] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [PurchaseOrderItems] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [PurchaseOrders] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [RawMaterialMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [RawMaterialStocks] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [Receipts] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [SalesOrderItems] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [SalesOrders] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [StockAdjustments] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [StockTransactions] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [StockTransfers] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [SubCategoryMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [sysdiagrams] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [UnitMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [UserTypeMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [VendorMasters] WITH CHECK CHECK CONSTRAINT ALL;
ALTER TABLE [WarehouseMasters] WITH CHECK CHECK CONSTRAINT ALL;

COMMIT TRANSACTION;
GO
